version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:23.6

jobs:
  install:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: npm run test

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./*

workflows:
  version: 2
  build-workflow:
    jobs:
      - install:
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)*/
